In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a.shape

(3,)

In [3]:
b = np.array([[1, 2, 3],[4, 5, 6]])
b.ndim

2

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
c = range(10000)

In [6]:
%timeit [i**3 for i in c]

768 μs ± 47.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [7]:
c_numpy = np.arange(10000)

In [8]:
%timeit c_numpy**3

17.4 μs ± 414 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [9]:
l1 = range(10000)
l2 = [i**2 for i in range(10000)]

In [10]:
%timeit list(map(lambda x,y: x*y, l1, l2))

984 μs ± 18 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [11]:
a1 = np.array(l1)
b1 = np.array(l2)

In [13]:
%timeit a1*b1

6.75 μs ± 601 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [15]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [24]:
np.full((3,3), 2.2, dtype=np.int64)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]], dtype=int64)

In [25]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [26]:
v= np.array([1,2,3])

In [27]:
v

array([1, 2, 3])

In [28]:
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [30]:
np.random.random()

0.9272685530802506

In [31]:
np.random.random([3,3])

array([[0.54917974, 0.53718995, 0.05941836],
       [0.22628863, 0.01749851, 0.05913382],
       [0.66075229, 0.76832044, 0.477403  ]])

In [32]:
a =np.linspace(1,50,100)